-- Replace specialty_tag Nurse/Wellbeing Advisor values with organizational role taxonomy.
-- Values: Support, Lead, Advisor, Coordinator, Board.
-- Existing rows (Nurse, Wellbeing Advisor) are cleared first so the new constraint can be added.

-- Clear values that will violate the new constraint
update public.user_profiles
  set specialty_tag = null
  where specialty_tag is not null
    and specialty_tag not in ('Support', 'Lead', 'Advisor', 'Coordinator', 'Board');

-- Drop old check constraint (name generated by Postgres from the inline CHECK in migration 20260606120000)
alter table public.user_profiles
  drop constraint if exists user_profiles_specialty_tag_check;

-- Add new constraint with expanded role taxonomy
alter table public.user_profiles
  add constraint user_profiles_specialty_tag_check
  check (specialty_tag in ('Support', 'Lead', 'Advisor', 'Coordinator', 'Board'));
